build: Android: add support for building all architectures in a single run
git-svn-id: https://svn.resiprocate.org/rep/resiprocate/main@10317 ddefafc4-47db-0310-ae44-fa13212b10f2

diff --git a/build/android-custom-ndk b/build/android-custom-ndk
--- a/build/android-custom-ndk
+++ b/build/android-custom-ndk
@@ -1,93 +1,110 @@
 #!/bin/bash
 set -e
 
+PLATFORM=android-9
+
+PROJECTS="rutil resip/stack resip/dum"
+
+NDK_DIST=${HOME}/ndk-prebuilt
+PROJECT=resip
+PROJECT_DIST=${NDK_DIST}/${PROJECT}
+
+MODS_DIR=build/android/modulations
+
 if [ -z "${NDK_HOME}" ];
 then
   echo "Please set NDK_HOME"
   exit 1
 fi
 
-PLATFORM=android-9
-
-MY_NDK=${HOME}/ws/resiprocate/resip-ndk
-
-#$NDK_HOME/build/tools/make-standalone-toolchain.sh --platform=$PLATFORM \
-#  --install-dir=$MY_NDK --system=linux-x86_64
-#exit 0
-
-export CROSS_COMPILE=arm-linux-androideabi
-export TOOLCHAIN_PREFIX=${CROSS_COMPILE}
-
-export SYSROOT=${MY_NDK}/sysroot
+if [ ! -d ${MODS_DIR} ];
+then
+  echo "Can't find directory ${MODS_DIR}"
+  exit 1
+fi
 
 # you need OpenSSL from
 #  https://github.com/guardianproject/openssl-android.git
-# clone it and run "ndk-build"
+# clone it and run "prebuilt/deploy-prebuilt.sh" or just "ndk-build"
 export OPENSSL_HOME=${HOME}/ws/openssl/openssl-android
 
-export PATH=${MY_NDK}/bin:$PATH
-export CPP=${TOOLCHAIN_PREFIX}-cpp
-export AR=${TOOLCHAIN_PREFIX}-ar
-export AS=${TOOLCHAIN_PREFIX}-as
-export NM=${TOOLCHAIN_PREFIX}-nm
-export CC=${TOOLCHAIN_PREFIX}-gcc
-export CXX=${TOOLCHAIN_PREFIX}-g++
-export LD=${TOOLCHAIN_PREFIX}-ld
-export RANLIB=${TOOLCHAIN_PREFIX}-ranlib
-
-export CPPFLAGS="${CPPFLAGS} -I${OPENSSL_HOME}/include"
-export LDFLAGS="${LDFLAGS} -L${OPENSSL_HOME}/libs/armeabi"
-
-# for 16 bit Thumb-1 (default is 32 bit ARM)
-export CPPFLAGS="${CPPFLAGS} -mthumb"
-# for ARMv7
-#export CPPFLAGS="${CPPFLAGS} -march=armv7-a -mfloat-abi=softfp"
-#export LDFLAGS="${LDFLAGS} -Wl,--fix-cortex-a8"
-
-autoreconf -fi
-
-./configure \
-  --host=${CROSS_COMPILE} \
-  --with-sysroot=${SYSROOT} \
-  --enable-android \
-  --with-ssl \
-  "$@"
+if [ ! -d ${OPENSSL_HOME} ];
+then
+  echo "Can't find ${OPENSSL_HOME}"
+  exit 1
+fi
 
 CPUS=`cat /proc/cpuinfo | grep -c ^proc`
 PAR=`expr $CPUS + 1`
 
-PROJECTS="rutil resip/stack resip/dum"
-for proj in $PROJECTS ;
+STAGE_PREBUILT=`mktemp -d`
+
+for MOD_SRC in ${MODS_DIR}/* ;
 do
-  make -C $proj clean
-  make -C $proj -j$PAR
+
+  echo "Trying modulation ${MOD_SRC} ..."
+  MOD_NAME=`basename ${MOD_SRC}`
+
+  export CPPFLAGS=""
+  export LDFLAGS=""
+
+  source ${MOD_SRC}
+
+  MY_NDK=`mktemp -d`
+  echo "Creating a toolchain in ${MY_NDK}"
+
+  ${NDK_HOME}/build/tools/make-standalone-toolchain.sh --platform=${PLATFORM} \
+    --install-dir=${MY_NDK} --system=linux-x86_64 --arch=${MOD_ARCH}
+
+  export CROSS_COMPILE
+  export TOOLCHAIN_PREFIX=${CROSS_COMPILE}
+
+  export SYSROOT=${MY_NDK}/sysroot
+
+  export PATH=${MY_NDK}/bin:$PATH
+  export CPP=${TOOLCHAIN_PREFIX}-cpp
+  export AR=${TOOLCHAIN_PREFIX}-ar
+  export AS=${TOOLCHAIN_PREFIX}-as
+  export NM=${TOOLCHAIN_PREFIX}-nm
+  export CC=${TOOLCHAIN_PREFIX}-gcc
+  export CXX=${TOOLCHAIN_PREFIX}-g++
+  export LD=${TOOLCHAIN_PREFIX}-ld
+  export RANLIB=${TOOLCHAIN_PREFIX}-ranlib
+
+  export CPPFLAGS="${CPPFLAGS} -I${OPENSSL_HOME}/include"
+  export LDFLAGS="${LDFLAGS} -L${OPENSSL_HOME}/libs/${MOD_NAME}"
+
+  autoreconf -fi
+
+  ./configure \
+    --libdir=/libs/${MOD_NAME} \
+    --host=${CROSS_COMPILE} \
+    --with-sysroot=${SYSROOT} \
+    --enable-android \
+    --with-ssl \
+    "$@"
+
+  for proj in $PROJECTS ;
+  do
+    make -C $proj clean
+    make -C $proj -j${PAR} DESTDIR=${STAGE_PREBUILT} install
+  done
+
+  #for proj in $PROJECTS ;
+  #do
+  #  make -C $proj -i -j$PAR check
+  #done
+
+  echo "Removing temporary toolchain ${MY_NDK} ..."
+  rm -rf "${MY_NDK}"
+
 done
 
-for proj in $PROJECTS ;
-do
-  make -C $proj -i -j$PAR check
-done
+echo "Copying libs into place ..."
+mkdir -p ${PROJECT_DIST}
+cp -r ${STAGE_PREBUILT}/libs/* ${PROJECT_DIST}
+cp build/android/prebuilt/Android.mk ${PROJECT_DIST}
+rm -rf "${STAGE_PREBUILT}"
 
-adb shell mkdir /sdcard/resip-test
-adb shell mkdir /sdcard/resip-test/bin
-adb shell mkdir /sdcard/resip-test/lib
-
-find . -name test* | grep .libs/test* | \
-  while read ;
-  do 
-    adb push $REPLY /sdcard/resip-test/bin/
-  done 
-
-find . -name lib*-1.9.so -exec adb push {} /sdcard/resip-test/lib/ \;
-
-for i in ${OPENSSL_HOME}/libs/armeabi/lib*.so ;
-do
-  adb push $i /sdcard/resip-test/lib/
-done
-
-adb push \
-  ${MY_NDK}/arm-linux-androideabi/lib/libgnustl_shared.so \
-  /sdcard/resip-test/lib/
-
-adb push build/run-android-tests.sh /sdcard/run.sh
+echo "All done"
 
